### ISSUE TITLE
hpcrun crashes when profiling AMG2006 on gpu.cs

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpctoolkit#125]
Application: AMG2006
Compiler: gcc 4.8.5, OpenMPI 3.1.0
Platform: gpu.cs.rice.edu

Profiling AMG application sometimes crashes (either profiling with **perf_events** or **realtime**). It's unknown the root cause of the problem. However, when it crashes,  the backtrace of the core dump consistently shows that it fails when openmpi tries to unwind:

```
#0  0x00007f653f1a90b8 in ?? () from /lib64/libgcc_s.so.1
#1  0x00007f653f1a9fb9 in _Unwind_Backtrace () from /lib64/libgcc_s.so.1
#2  0x00007f653fae7f16 in backtrace () from /lib64/libc.so.6
#3  0x00007f653e045276 in opal_backtrace_print () from /projects/pkgs/openmpi-3.1.0/lib/libopen-pal.so.40
#4  0x00007f653e0402ba in show_stackframe () from /projects/pkgs/openmpi-3.1.0/lib/libopen-pal.so.40
#5  0x00007f65407e828b in monitor_signal_handler (sig=11, info=0x7f652847a0f0, context=0x7f6528479fc0) at ../../libmonitor/src/signal.c:271
#6  <signal handler called>
#7  0xffffffffb5c9df25 in ?? ()
#8  0xffffffffb6329fa6 in ?? ()
#9  0xffffffffb631c362 in ?? ()
#10 0x0000000000000000 in ?? ()
```

Use the following script to capture the problem:
```
for i in {1..100}
do
  echo "test $i"
  mpirun -np 8 ~/pkgs/hpctoolkit-fix/bin/hpcrun -dd LINUX_PERF -e cycles -e MEM_TRANS_RETIRED:LATENCY_ABOVE_THRESHOLD -e MEM_LOAD_UOPS_L3_HIT_RETIRED:XSNP_MISS  -e faults -t  ./amg2006 -P 2 2 2  -r 18 18 18 >> /tmp/amg.output 2>> /tmp/amg.err

  if [ -e  "core"*  ]; then
    echo "Core file (segmentation fault occurs "
    exit 9
  fi
  rm -rf  hpctoolkit-amg2006-measurements
done
```

**Comment by laksono** [comment]
Fixed in fix-perf branch #126
