### ISSUE TITLE
BLOCKTIME event crashes

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpctoolkit#189]
Tested platforms: x86 and Arm
Branch: master
Cause: Incorrect use of metric kind. The block-time  and Linux perf_events  have different metric-kind. When genevent_set is triggered, it queries the number of metrics, and it returns 0 since block-time event is not part of Linux perf_event metric kind.

Call stack from the core file:
```
(gdb) bt
#0  0x0000ffff8235cc48 in record_sample (current=0xffff7ec4da90, mmap_data=0xffffc384c3f0, context=0xffffc384c770, sv=0xffffc384c5b0) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:549
#1  0x0000ffff8235e100 in perf_event_handler (sig=38, siginfo=0xffffc384c6f0, context=0xffffc384c770) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:1163
#2  0x0000ffff822deab8 in monitor_signal_handler (sig=38, info=0xffffc384c6f0, context=0xffffc384c770) at signal.c:218
#3  <signal handler called>

(gdb) l
544
545       // check if this event is multiplexed. we need to notify the user that a multiplexed
546       //  event is not accurate at all.
547       // Note: perf event can report the scale to be close to 1 (like 1.02 or 0.99).
548       //       we need to use a range of value to see if it's multiplexed or not
549       info_aux->is_multiplexed    |= (scale_f>PERF_MULTIPLEX_RANGE);
550
551       // case of multiplexed or frequency-based sampling, we need to store the mean and
552       // the standard deviation of the sampling period
553       info_aux->num_samples++;
(gdb) p info_aux
$1 = (metric_aux_info_t *) 0x0
```
`info_aux` is null because it doesn't get the correct number of metrics. Hence, it allocates zero byte:
```
 930   int num_metrics = hpcrun_get_num_metrics(lnux_kind);
 931
...
 941
 942   size_t mem_metrics_size = num_metrics * sizeof(metric_aux_info_t);
 943   metric_aux_info_t* aux_info = (metric_aux_info_t*) hpcrun_malloc(mem_metrics_size);
 944   memset(aux_info, 0, mem_metrics_size);
 945
 946   thread_data_t* td = hpcrun_get_thread_data();
 947
 948   td->core_profile_trace_data.perf_event_info = aux_info;
```

**Comment by mxz297** [comment]
@jmellorcrummey Can we close this issue?
