### ISSUE TITLE
Sporadic hpctraceviewer failures with OpenJDK 1.8.0 

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#32]
hpctraceviewer hpctoolkit-openmp-parse-database/
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
java.lang.NullPointerException
        at org.eclipse.swt.graphics.GC.drawImage(GC.java:789)
        at org.eclipse.swt.graphics.GC.drawImage(GC.java:769)
        at edu.rice.cs.hpc.traceviewer.depth.DepthViewPaint.drawPainting(DepthViewPaint.java:97)
        at edu.rice.cs.hpc.traceviewer.painter.BaseViewPaint.endPainting(BaseViewPaint.java:317)
        at edu.rice.cs.hpc.traceviewer.painter.BaseViewPaint.executePaint(BaseViewPaint.java:249)
        at edu.rice.cs.hpc.traceviewer.painter.BaseViewPaint.paint(BaseViewPaint.java:199)
        at edu.rice.cs.hpc.traceviewer.painter.BaseViewPaint.run(BaseViewPaint.java:91)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/32)
