### ISSUE TITLE
Invalid load module

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpctoolkit#49]
Platform: ori
GCC 6.3.1.
Linux  kernel 4.13.16
HPCToolkit branch: master (the latest one)

hpcrun command:

>~/pkgs/hpctoolkit-master/bin/hpcrun -e CYCLES -e INSTRUCTIONS -e BLOCKTIME ~/pkgs/tar-1.29/bin/tar xzf eclipse-rcp-indigo-linux-gtk-x86_64.tar.gz

Somehow, the tar command results **TWO** hpcrun and log files.
>$ ls -l hpctoolkit-tar-measurements/
```
total 208
-rw-r--r--. 1 la5 hpc 195919 Jan 30 09:16 tar-000000-000-07a86c74-28063-0.hpcrun
-rw-r--r--. 1 la5 hpc    421 Jan 30 09:16 tar-000000-000-07a86c74-28063-0.log
-rw-r--r--. 1 la5 hpc   5096 Jan 30 09:16 tar-000000-000-07a86c74-28082-0.hpcrun
-rw-r--r--. 1 la5 hpc    403 Jan 30 09:16 tar-000000-000-07a86c74-28082-0.log
```

One has 155267 samples, the other one has only 6 recorded samples.

==> hpctoolkit-tar-measurements/tar-000000-000-07a86c74-28063-0.log <==
SUMMARY: samples: 155267 (recorded: 155256, blocked: 11, errant: 0, trolled: 0, yielded: 0),

==> hpctoolkit-tar-measurements/tar-000000-000-07a86c74-28082-0.log <==
SUMMARY: samples: 11 (recorded: 6, blocked: 5, errant: 0, trolled: 0, yielded: 0),

hpcprof command:
> $ ~/pkgs/hpctoolkit-master/bin/hpcprof -S ../tar.hpcstruct  hpctoolkit-tar-measurements/
```
WARNING: hpctoolkit-tar-measurements/tar-000000-000-07a86c74-28082-0.hpcrun: epoch 1: CCT node 106 has invalid load module: 24
WARNING: hpctoolkit-tar-measurements/tar-000000-000-07a86c74-28082-0.hpcrun: epoch 1: CCT node 108 has invalid load module: 24
WARNING: hpctoolkit-tar-measurements/tar-000000-000-07a86c74-28082-0.hpcrun: epoch 1: CCT node 110 has invalid load module: 24
WARNING: hpctoolkit-tar-measurements/tar-000000-000-07a86c74-28082-0.hpcrun: epoch 1: CCT node 112 has invalid load module: 24
WARNING: hpctoolkit-tar-measurements/tar-000000-000-07a86c74-28082-0.hpcrun: epoch 1: CCT node 114 has invalid load module: 24
```

Using hpcproftt command, it seems we mix up the kernel load module ID.
>$ ~/pkgs/hpctoolkit-master/bin/hpcproftt --dump hpctoolkit-tar-measurements/tar-000000-000-07a86c74-28082-0.hpcrun | less
```
[loadmap: (num-entries: 23)
  [(id: 1) (nm: /home/la5/pkgs/tar-1.29/bin/tar) (flg: 0x0)]
  [(id: 23) (nm: /usr/lib64/libresolv-2.24.so) (flg: 0x0)]
]
...
  [node: (id: 106) (id-parent: 104) (lm-id: 24) (lm-ip: 0xffffffff8489e777)
  (metrics: 0  0  0  0)
  ]
  [node: (id: 108) (id-parent: 106) (lm-id: 24) (lm-ip: 0xffffffff84289019)
  (metrics: 0  0  0  0)
  ]

```

**Comment by laksono** [comment]
Has been fixed in commit 5570eaa3bbef05cbb3a5145c1d1db36b9ba4f8f5

**Comment by laksono** [comment]
This problems still exists on ARM machine:
```
[la5@arm1 example1]$ ~/pkgs/hpctoolkit-kernel/bin/hpcprof -S ./nekbone.hpcstruct   hpctoolkit-nekbone-measurements/                                             
WARNING: hpctoolkit-nekbone-measurements/nekbone-000000-000-07a8d174-23821-0.hpcrun: epoch 1: CCT node 6243 has invalid load module: 15612                      
WARNING: hpctoolkit-nekbone-measurements/nekbone-000000-000-07a8d174-23821-0.hpcrun: epoch 1: CCT node 3951 has invalid load module: 53904                      
WARNING: hpctoolkit-nekbone-measurements/nekbone-000000-000-07a8d174-23821-0.hpcrun: epoch 1: CCT node 1992 has invalid load module: 48336                      
WARNING: hpctoolkit-nekbone-measurements/nekbone-000000-000-07a8d174-23821-0.hpcrun: epoch 1: CCT node 1995 has invalid load module: 48320                      
WARNING: hpctoolkit-nekbone-measurements/nekbone-000000-000-07a8d174-23821-0.hpcrun: epoch 1: CCT node 5984 has invalid load module: 47068                      
WARNING: hpctoolkit-nekbone-measurements/nekbone-000000-000-07a8d174-23821-0.hpcrun: epoch 1: CCT node 5987 has invalid load module: 12508                      
WARNING: hpctoolkit-nekbone-measurements/nekbone-000000-000-07a8d174-23821-0.hpcrun: epoch 1: CCT node 3948 has invalid load module: 53936  
```
At the end, it generates an error message that it cannot find linux-vdso (not sure if it's related):
```
ERROR: Cannot fully process samples because of errors reading load modules:
  'linux-vdso.so.1': No such file or directory

        [../../../../src/lib/analysis/CallPath.cpp:368]
msg: Populating Experiment database: /home/la5/git/hpctoolkit-tests/applications/nekbone-2.3.4/test/example1/hpctoolkit-nekbone-database
```
To generate this problem, run nekbone with the following command:
```
[la5@arm1 example1]$ mpirun  -np 2 ~/pkgs//hpctoolkit-kernel/bin/hpcrun -dd LINUX_PERF -e cycles -t -e instructions  ./nekbone                                                            
...
[la5@arm1 example1]$ ~/pkgs/hpctoolkit-kernel/bin/hpcstruct  nekbone                                                                                            
[la5@arm1 example1]$ ~/pkgs/hpctoolkit-kernel/bin/hpcprof -S ./nekbone.hpcstruct   hpctoolkit-nekbone-measurements/
```

**Comment by jmellorcrummey** [comment]
@laksono: please rerun this test on ARM with the version of nekbone that you have. I believe that this should have been fixed in master by commit 01f30ea

**Comment by laksono** [comment]
Perhaps unrelated issue, there's a deadlock with OpenMPI Init if profiled with hpctoolkit's REALTIME or perf_events' CYCLE

AMG2006 works fine without hpctoolkit:
```
[la5@arm1 test]$ time ./amg2006 -P 1 1 1   -r 10 10 10
...
real    0m7.140s
user    0m14.706s
sys     0m0.248s
```
Error when profiled with REALTIME:
```
$ /home/la5/pkgs/hpctoolkit-master/bin/hpcrun -dd LINUX_PERF  -e REALTIME@5000 ./amg2006 -P 1 1 1  -r 10 10  10
[arm1.cs.rice.edu:03399] PMIX ERROR: ERROR in file ../../../../../../../opal/mca/pmix/pmix2x/pmix/src/dstore/pmix_esh.c at line 1658
[arm1.cs.rice.edu:03399] PMIX ERROR: OUT-OF-RESOURCE in file ../../../../../../../opal/mca/pmix/pmix2x/pmix/src/dstore/pmix_esh.c at line 1759
[arm1.cs.rice.edu:03399] PMIX ERROR: OUT-OF-RESOURCE in file ../../../../../../../opal/mca/pmix/pmix2x/pmix/src/dstore/pmix_esh.c at line 1123
[arm1.cs.rice.edu:03399] PMIX ERROR: OUT-OF-RESOURCE in file ../../../../../../../opal/mca/pmix/pmix2x/pmix/src/common/pmix_jobdata.c at line 112
[arm1.cs.rice.edu:03399] PMIX ERROR: OUT-OF-RESOURCE in file ../../../../../../../opal/mca/pmix/pmix2x/pmix/src/common/pmix_jobdata.c at line 392
[arm1.cs.rice.edu:03399] PMIX ERROR: OUT-OF-RESOURCE in file ../../../../../../../opal/mca/pmix/pmix2x/pmix/src/server/pmix_server.c at line 518
```
Using gdb:
```
(gdb) bt
#0  0x000040003e5cc754 in __read_nocancel () from /lib64/libpthread.so.0
#1  0x000040003f469ae0 in rte_init.part () from /projects/pkgs/openmpi-3.0.0/lib/openmpi/mca_ess_singleton.so
#2  0x000040003e8e02ac in orte_init () from /projects/pkgs/openmpi-3.0.0/lib/libopen-rte.so.40
#3  0x000040003e4912f0 in ompi_mpi_init () from /projects/pkgs/openmpi-3.0.0/lib/libmpi.so.40
#4  0x000040003e4b8314 in PMPI_Init () from /projects/pkgs/openmpi-3.0.0/lib/libmpi.so.40
#5  0x000040003e33df58 in MPI_Init (argc=0xfffff2f500ec, argc@entry=0xfffff2f501fc, argv=0xfffff2f500e0, argv@entry=0xfffff2f501f0) at ../../libmonitor/src/mpi_init_c.c:33
#6  0x0000000000401ed8 in main (argc=<optimized out>, argv=<optimized out>) at amg2006.c:1615
```

**Comment by laksono** [comment]
My configuration:
```
  $ ../configure --prefix=/home/la5/pkgs/hpctoolkit-master --with-externals=/home/la5/pkgs/externals --enable-develop --enable-mpi
```
GCC: gcc (GCC) 7.3.1 20180130 (Red Hat 7.3.1-2)

```
$ which  mpicc
/projects/pkgs/openmpi-3.0.0/bin/mpic
```

**Comment by jmellorcrummey** [comment]
Please close this and open appropriate bug reports. The history of this is as follows

- invalid load module on ori (I believe that this should already be fixed in master)
- invalid load module on arm (I believe that this should also already be fixed in master)
- nekbone complaint about vdso (should be a separate bug report)
- AMG2006 complaint about OpenMPI (on ARM?)

There is no reason why these three things should be in the same bug report. They are four completely separate issues that should be tracked and addressed separately.
