### ISSUE TITLE
hpcrun on ARM: Blocked when profiling nekbone and AMG Mk

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpctoolkit#78]
Command:
```
export OMP_NUM_THREADS=5
/home/la5/pkgs/hpctoolkit-master/bin/hpcrun -dd LINUX_PERF -d -e cycles -e instructions  -t  ./nekbone 
```
The problem is that the kernel delivers the first signal just after enabling the perf_event, and during unwinding.  It seems libunwind unblock the signal, hence the kernel keeps delivering signals to hpcrun.
Unfortunately just before we check if we are inside hpcrun or not (when we call hpcrun_context_pc to get the pc), there's a second signal is delivered. 
Again, within this signal handler, just before we check if we are inside hpcrun, the third signal is delivered ! .... as so on.

```
#0  0x000040002d15441c in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x000040002d14ceac in pthread_mutex_lock () from /lib64/libpthread.so.0
#2  0x000040002d363498 in _ULaarch64_init () at ../../libunwind/src/aarch64/Gglobal.c:40
#3  0x000040002d3637d8 in unw_init_local_common (cursor=0xffffff6b1448, uc=0xffffff6b27f0, use_prev_instr=1) at ../../libunwind/src/aarch64/Ginit_local.c:45
#4  0x000040002cc34540 in hpcrun_context_pc (context=0xffffff6b27f0) at ../../../../src/tool/hpcrun/utilities/arch/libunwind/libunwind-context-pc.c:62
#5  0x000040002cc2fa08 in perf_event_handler (sig=38, siginfo=0xffffff6b2770, context=0xffffff6b27f0) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:943
#6  0x000040002cc8ea90 in monitor_signal_handler (sig=38, info=0xffffff6b2770, context=0xffffff6b27f0) at ../../libmonitor/src/signal.c:217
#7  <signal handler called>

#8  0x000040002d205ec0 in memset () from /lib64/libc.so.6
#9  0x000040002d363730 in _ULaarch64_local_addr_space_init () at ../../libunwind/src/aarch64/Ginit.c:176
#10 0x000040002d3634e4 in _ULaarch64_init () at ../../libunwind/src/aarch64/Gglobal.c:51
#11 0x000040002d3637d8 in unw_init_local_common (cursor=0xffffff6b3ae8, uc=0xffffff6b4e90, use_prev_instr=1) at ../../libunwind/src/aarch64/Ginit_local.c:45
#12 0x000040002cc34540 in hpcrun_context_pc (context=0xffffff6b4e90) at ../../../../src/tool/hpcrun/utilities/arch/libunwind/libunwind-context-pc.c:62
#13 0x000040002cc2fa08 in perf_event_handler (sig=38, siginfo=0xffffff6b4e10, context=0xffffff6b4e90) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:943
#14 0x000040002cc8ea90 in monitor_signal_handler (sig=38, info=0xffffff6b4e10, context=0xffffff6b4e90) at ../../libmonitor/src/signal.c:217
#15 <signal handler called>

#16 0x000040002d1acdac in sigprocmask () from /lib64/libc.so.6
#17 0x000040002cc8fd94 in sigprocmask (how=how@entry=2, set=0xffffff6b6188, set@entry=0x40002d3a1100 <_UIaarch64_full_mask>, oldset=oldset@entry=0xffffff6b6420)
    at ../../libmonitor/src/signal.c:794
#18 0x000040002d363480 in _ULaarch64_init () at ../../libunwind/src/aarch64/Gglobal.c:40
#19 0x000040002d3637d8 in unw_init_local_common (cursor=0xffffff6b64f8, uc=0xffffff6b78a0, use_prev_instr=1) at ../../libunwind/src/aarch64/Ginit_local.c:45
#20 0x000040002cc34540 in hpcrun_context_pc (context=0xffffff6b78a0) at ../../../../src/tool/hpcrun/utilities/arch/libunwind/libunwind-context-pc.c:62
#21 0x000040002cc2fa08 in perf_event_handler (sig=38, siginfo=0xffffff6b7820, context=0xffffff6b78a0) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:943
#22 0x000040002cc8ea90 in monitor_signal_handler (sig=38, info=0xffffff6b7820, context=0xffffff6b78a0) at ../../libmonitor/src/signal.c:217
#23 <signal handler called>

#24 0x000040002d1acdac in sigprocmask () from /lib64/libc.so.6
#25 0x000040002cc8fd94 in sigprocmask (how=how@entry=2, set=0xffffff6b8b98, set@entry=0x40002d3a1100 <_UIaarch64_full_mask>, oldset=oldset@entry=0xffffff6b8e30)
    at ../../libmonitor/src/signal.c:794
#26 0x000040002d363480 in _ULaarch64_init () at ../../libunwind/src/aarch64/Gglobal.c:40
#27 0x000040002d3637d8 in unw_init_local_common (cursor=0xffffff6b8f08, uc=0xffffff6ba2b0, use_prev_instr=1) at ../../libunwind/src/aarch64/Ginit_local.c:45
#28 0x000040002cc34540 in hpcrun_context_pc (context=0xffffff6ba2b0) at ../../../../src/tool/hpcrun/utilities/arch/libunwind/libunwind-context-pc.c:62
#29 0x000040002cc2fa08 in perf_event_handler (sig=38, siginfo=0xffffff6ba230, context=0xffffff6ba2b0) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:943
#30 0x000040002cc8ea90 in monitor_signal_handler (sig=38, info=0xffffff6ba230, context=0xffffff6ba2b0) at ../../libmonitor/src/signal.c:217
#31 <signal handler called>

#32 0x000040002d1acdac in sigprocmask () from /lib64/libc.so.6
#33 0x000040002cc8fd94 in sigprocmask (how=how@entry=2, set=0xffffff6bb5a8, set@entry=0x40002d3a1100 <_UIaarch64_full_mask>, oldset=oldset@entry=0xffffff6bb840)
    at ../../libmonitor/src/signal.c:794
#34 0x000040002d363480 in _ULaarch64_init () at ../../libunwind/src/aarch64/Gglobal.c:40
#35 0x000040002d3637d8 in unw_init_local_common (cursor=0xffffff6bb918, uc=0xffffff6bccc0, use_prev_instr=1) at ../../libunwind/src/aarch64/Ginit_local.c:45
#36 0x000040002cc34540 in hpcrun_context_pc (context=0xffffff6bccc0) at ../../../../src/tool/hpcrun/utilities/arch/libunwind/libunwind-context-pc.c:62
#37 0x000040002cc2fa08 in perf_event_handler (sig=38, siginfo=0xffffff6bcc40, context=0xffffff6bccc0) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:943
#38 0x000040002cc8ea90 in monitor_signal_handler (sig=38, info=0xffffff6bcc40, context=0xffffff6bccc0) at ../../libmonitor/src/signal.c:217
#39 <signal handler called>

#40 0x000040002d1acdac in sigprocmask () from /lib64/libc.so.6
#41 0x000040002cc8fd94 in sigprocmask (how=how@entry=2, set=0xffffff6bdfb8, set@entry=0x40002d3a1100 <_UIaarch64_full_mask>, oldset=oldset@entry=0xffffff6be250)
    at ../../libmonitor/src/signal.c:794
#42 0x000040002d363480 in _ULaarch64_init () at ../../libunwind/src/aarch64/Gglobal.c:40
#43 0x000040002d3637d8 in unw_init_local_common (cursor=0xffffff6be328, uc=0xffffff6bf6d0, use_prev_instr=1) at ../../libunwind/src/aarch64/Ginit_local.c:45
#44 0x000040002cc34540 in hpcrun_context_pc (context=0xffffff6bf6d0) at ../../../../src/tool/hpcrun/utilities/arch/libunwind/libunwind-context-pc.c:62
#45 0x000040002cc2fa08 in perf_event_handler (sig=38, siginfo=0xffffff6bf650, context=0xffffff6bf6d0) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:943
#46 0x000040002cc8ea90 in monitor_signal_handler (sig=38, info=0xffffff6bf650, context=0xffffff6bf6d0) at ../../libmonitor/src/signal.c:217
#47 <signal handler called>

#48 0x000040002d25d7ec in ioctl () from /lib64/libc.so.6
#49 0x000040002cc2e048 in perf_start_all (nevents=1, event_thread=0x40002de76f00) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:232
#50 0x000040002cc2ee50 in start (self=0x40002cc7c790 <_linux_perf_obj>) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:622
#51 0x000040002cc1db2c in hpcrun_all_sources_start () at ../../../../src/tool/hpcrun/sample_sources_all.c:261
#52 0x000040002cc16ffc in hpcrun_init_internal (is_child=false) at ../../../../src/tool/hpcrun/main.c:512
#53 0x000040002cc17964 in monitor_init_process (argc=0x40002ccbe0d8 <monitor_argc>, argv=0xffffff6c1418, data=0x0) at ../../../../src/tool/hpcrun/main.c:837
#54 0x000040002cc9632c in monitor_begin_process_fcn (user_data=0x0, is_fork=<optimized out>) at ../../libmonitor/src/main.c:262
#55 0x000040002cc967c8 in monitor_main (argc=1, argv=0xffffff6c1418, envp=0xffffff6c1428) at ../../libmonitor/src/main.c:488
#56 0x000040002d1979ec in __libc_start_main () from /lib64/libc.so.6
#57 0x000040002cc95c84 in __libc_start_main (main=0x402850 <main>, argc=1, argv=0xffffff6c1418, init=0x49aee0 <__libc_csu_init>, fini=0x49af60 <__libc_csu_fini>,
    rtld_fini=0x40002cbd30f8 <_dl_fini>, stack_end=<optimized out>) at ../../libmonitor/src/main.c:539
#58 0x00000000004028a8 in _start ()
```
Similar problem with AMG micro kernel, it blocks at `__lll_lock_wait` function.
```
/home/la5/pkgs/hpctoolkit-master/bin/hpcrun -dd LINUX_PERF -e cycles -e instructions -d -t ./AMGMk-gcc
...
#0  0x000040003748241c in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x000040003747aeac in pthread_mutex_lock () from /lib64/libpthread.so.0
#2  0x0000400037691498 in _ULaarch64_init () at ../../libunwind/src/aarch64/Gglobal.c:40
#3  0x00004000376917d8 in unw_init_local_common (cursor=0xffffe1dec5e8, uc=0xffffe1ded990, use_prev_instr=1) at ../../libunwind/src/aarch64/Ginit_local.c:45
#4  0x000040003739b540 in hpcrun_context_pc (context=0xffffe1ded990) at ../../../../src/tool/hpcrun/utilities/arch/libunwind/libunwind-context-pc.c:62
#5  0x0000400037396a08 in perf_event_handler (sig=38, siginfo=0xffffe1ded910, context=0xffffe1ded990) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:943
#6  0x00004000373f5a90 in monitor_signal_handler (sig=38, info=0xffffe1ded910, context=0xffffe1ded990) at ../../libmonitor/src/signal.c:217
#7  <signal handler called>

#8  0x0000400037533ec0 in memset () from /lib64/libc.so.6
#9  0x0000400037691730 in _ULaarch64_local_addr_space_init () at ../../libunwind/src/aarch64/Ginit.c:176
#10 0x00004000376914e4 in _ULaarch64_init () at ../../libunwind/src/aarch64/Gglobal.c:51
#11 0x00004000376917d8 in unw_init_local_common (cursor=0xffffe1deec88, uc=0xffffe1df0030, use_prev_instr=1) at ../../libunwind/src/aarch64/Ginit_local.c:45
#12 0x000040003739b540 in hpcrun_context_pc (context=0xffffe1df0030) at ../../../../src/tool/hpcrun/utilities/arch/libunwind/libunwind-context-pc.c:62
#13 0x0000400037396a08 in perf_event_handler (sig=38, siginfo=0xffffe1deffb0, context=0xffffe1df0030) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:943
#14 0x00004000373f5a90 in monitor_signal_handler (sig=38, info=0xffffe1deffb0, context=0xffffe1df0030) at ../../libmonitor/src/signal.c:217
#15 <signal handler called>

#16 0x00004000374dadac in sigprocmask () from /lib64/libc.so.6
#17 0x00004000373f6d8c in sigprocmask (how=how@entry=2, set=0xffffe1df1328, set@entry=0x4000376cf100 <_UIaarch64_full_mask>, oldset=oldset@entry=0xffffe1df15c0)
    at ../../libmonitor/src/signal.c:794
#18 0x0000400037691480 in _ULaarch64_init () at ../../libunwind/src/aarch64/Gglobal.c:40
#19 0x00004000376917d8 in unw_init_local_common (cursor=0xffffe1df1698, uc=0xffffe1df2a40, use_prev_instr=1) at ../../libunwind/src/aarch64/Ginit_local.c:45
#20 0x000040003739b540 in hpcrun_context_pc (context=0xffffe1df2a40) at ../../../../src/tool/hpcrun/utilities/arch/libunwind/libunwind-context-pc.c:62
#21 0x0000400037396a08 in perf_event_handler (sig=38, siginfo=0xffffe1df29c0, context=0xffffe1df2a40) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:943
#22 0x00004000373f5a90 in monitor_signal_handler (sig=38, info=0xffffe1df29c0, context=0xffffe1df2a40) at ../../libmonitor/src/signal.c:217
#23 <signal handler called>

#24 0x00004000374dadac in sigprocmask () from /lib64/libc.so.6
#25 0x00004000373f6d8c in sigprocmask (how=how@entry=2, set=0xffffe1df3d38, set@entry=0x4000376cf100 <_UIaarch64_full_mask>, oldset=oldset@entry=0xffffe1df3fd0)
    at ../../libmonitor/src/signal.c:794
#26 0x0000400037691480 in _ULaarch64_init () at ../../libunwind/src/aarch64/Gglobal.c:40
#27 0x00004000376917d8 in unw_init_local_common (cursor=0xffffe1df40a8, uc=0xffffe1df5450, use_prev_instr=1) at ../../libunwind/src/aarch64/Ginit_local.c:45
#28 0x000040003739b540 in hpcrun_context_pc (context=0xffffe1df5450) at ../../../../src/tool/hpcrun/utilities/arch/libunwind/libunwind-context-pc.c:62
#29 0x0000400037396a08 in perf_event_handler (sig=38, siginfo=0xffffe1df53d0, context=0xffffe1df5450) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:943
#30 0x00004000373f5a90 in monitor_signal_handler (sig=38, info=0xffffe1df53d0, context=0xffffe1df5450) at ../../libmonitor/src/signal.c:217
#31 <signal handler called>

#32 0x00004000374dadac in sigprocmask () from /lib64/libc.so.6
#33 0x00004000373f6d8c in sigprocmask (how=how@entry=2, set=0xffffe1df6748, set@entry=0x4000376cf100 <_UIaarch64_full_mask>, oldset=oldset@entry=0xffffe1df69e0)
    at ../../libmonitor/src/signal.c:794
#34 0x0000400037691480 in _ULaarch64_init () at ../../libunwind/src/aarch64/Gglobal.c:40
#35 0x00004000376917d8 in unw_init_local_common (cursor=0xffffe1df6ab8, uc=0xffffe1df7e60, use_prev_instr=1) at ../../libunwind/src/aarch64/Ginit_local.c:45
#36 0x000040003739b540 in hpcrun_context_pc (context=0xffffe1df7e60) at ../../../../src/tool/hpcrun/utilities/arch/libunwind/libunwind-context-pc.c:62
#37 0x0000400037396a08 in perf_event_handler (sig=38, siginfo=0xffffe1df7de0, context=0xffffe1df7e60) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:943
#38 0x00004000373f5a90 in monitor_signal_handler (sig=38, info=0xffffe1df7de0, context=0xffffe1df7e60) at ../../libmonitor/src/signal.c:217
#39 <signal handler called>

#40 0x00004000374dadac in sigprocmask () from /lib64/libc.so.6
#41 0x00004000373f6d8c in sigprocmask (how=how@entry=2, set=0xffffe1df9158, set@entry=0x4000376cf100 <_UIaarch64_full_mask>, oldset=oldset@entry=0xffffe1df93f0)
    at ../../libmonitor/src/signal.c:794
#42 0x0000400037691480 in _ULaarch64_init () at ../../libunwind/src/aarch64/Gglobal.c:40
#43 0x00004000376917d8 in unw_init_local_common (cursor=0xffffe1df94c8, uc=0xffffe1dfa870, use_prev_instr=1) at ../../libunwind/src/aarch64/Ginit_local.c:45
#44 0x000040003739b540 in hpcrun_context_pc (context=0xffffe1dfa870) at ../../../../src/tool/hpcrun/utilities/arch/libunwind/libunwind-context-pc.c:62
#45 0x0000400037396a08 in perf_event_handler (sig=38, siginfo=0xffffe1dfa7f0, context=0xffffe1dfa870) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:943
#46 0x00004000373f5a90 in monitor_signal_handler (sig=38, info=0xffffe1dfa7f0, context=0xffffe1dfa870) at ../../libmonitor/src/signal.c:217
#47 <signal handler called>

#48 0x000040003758b7ec in ioctl () from /lib64/libc.so.6
#49 0x0000400037395048 in perf_start_all (nevents=2, event_thread=0x400037f8eff0) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:232
#50 0x0000400037395e50 in start (self=0x4000373e3790 <_linux_perf_obj>) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:622
#51 0x0000400037384b2c in hpcrun_all_sources_start () at ../../../../src/tool/hpcrun/sample_sources_all.c:261
#52 0x000040003737dffc in hpcrun_init_internal (is_child=false) at ../../../../src/tool/hpcrun/main.c:512
#53 0x000040003737e964 in monitor_init_process (argc=0x4000374250d0 <monitor_argc>, argv=0xffffe1dfc5b8, data=0x0) at ../../../../src/tool/hpcrun/main.c:837
#54 0x00004000373fd324 in monitor_begin_process_fcn (user_data=0x0, is_fork=<optimized out>) at ../../libmonitor/src/main.c:262
#55 0x00004000373fd7c0 in monitor_main (argc=1, argv=0xffffe1dfc5b8, envp=0xffffe1dfc5c8) at ../../libmonitor/src/main.c:488
#56 0x00004000374c59ec in __libc_start_main () from /lib64/libc.so.6
#57 0x00004000373fcc7c in __libc_start_main (main=0x400c50 <main>, argc=1, argv=0xffffe1dfc5b8, init=0x4050c0 <__libc_csu_init>, fini=0x405140 <__libc_csu_fini>,
    rtld_fini=0x40003733a0f8 <_dl_fini>, stack_end=<optimized out>) at ../../libmonitor/src/main.c:539
#58 0x0000000000400e28 in _start ()
```

**Comment by mwkrentel** [comment]
Now fixed with patches to libmonitor and externals.
