### ISSUE TITLE
hpctraceviewer crashes on Cori when enlarging the window

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpctoolkit#87]
Java version:
```
Java(TM) SE Runtime Environment (build pxa6470_27sr4fp15-20171116_01(SR4 FP15))
IBM J9 VM (build 2.7, JRE 1.7.0 Linux amd64-64 Compressed References 20171011_366929 (JIT enabled, AOT enabled)
J9VM - R27_Java727_SR4_20171011_1720_B366929
JIT  - tr.r13.java_20171011_366929
GC   - R27_Java727_SR4_20171011_1720_B366929_CMPRSS
J9CL - 20171011_366929)
JCL - 20171109_01 based on Oracle jdk7u161-b13
```
Call stack of the crash:
```
java.lang.NullPointerException
        at org.eclipse.swt.graphics.GC.drawImage(GC.java:789)
        at org.eclipse.swt.graphics.GC.drawImage(GC.java:769)
        at edu.rice.cs.hpc.traceviewer.depth.DepthViewPaint.drawPainting(DepthViewPaint.java:97)
        at edu.rice.cs.hpc.traceviewer.painter.BaseViewPaint.endPainting(BaseViewPaint.java:312)
        at edu.rice.cs.hpc.traceviewer.painter.BaseViewPaint.executePaint(BaseViewPaint.java:247)
        at edu.rice.cs.hpc.traceviewer.painter.BaseViewPaint.paint(BaseViewPaint.java:197)
        at edu.rice.cs.hpc.traceviewer.painter.BaseViewPaint.run(BaseViewPaint.java:89)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```
Additional error message:
```
java: cairo-surface.c:956: cairo_surface_destroy: Assertion `(_cairo_atomic_int_get (&(&surface->ref_count)->ref_count) > 0)' failed.
JVMDUMP039I Processing dump event "abort", detail "" at 2018/05/26 04:44:11 - please wait.
JVMDUMP032I JVM requested System dump using '/global/u2/l/laksono/svn/hpctoolkit-tests/applications/AMG2006/test/core.20180526.044411.6911.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %e" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.7073.

JVMDUMP012E Error in System dump: The core file created by child process with pid = 7073 was not found. Expected to find core file with name "/global/u2/l/laksono/svn/hpctoolkit-tests/applications/AMG2006/test/core.7073"
JVMDUMP032I JVM requested Java dump using '/global/u2/l/laksono/svn/hpctoolkit-tests/applications/AMG2006/test/javacore.20180526.044411.6911.0002.txt' in response to an event
JVMDUMP010I Java dump written to /global/u2/l/laksono/svn/hpctoolkit-tests/applications/AMG2006/test/javacore.20180526.044411.6911.0002.txt
JVMDUMP032I JVM requested Snap dump using '/global/u2/l/laksono/svn/hpctoolkit-tests/applications/AMG2006/test/Snap.20180526.044411.6911.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /global/u2/l/laksono/svn/hpctoolkit-tests/applications/AMG2006/test/Snap.20180526.044411.6911.0003.trc
JVMDUMP007I JVM Requesting JIT dump using '/global/u2/l/laksono/svn/hpctoolkit-tests/applications/AMG2006/test/jitdump.20180526.044411.6911.0004.dmp'

#JITDUMP:  vmThread=0000000000557C00 Recursive crash occurred. Aborting JIT dump.JVMDUMP010I JIT dump written to /global/u2/l/laksono/svn/hpctoolkit-tests/applications/AMG2006/test/jitdump.20180526.044411.6911.0004.dmp
JVMDUMP013I Processed dump event "abort", detail "".
```

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/87)
