### ISSUE TITLE
hpcprof-mpi fails on vesta

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#93]
hpcprof-mpi fails when analyzing performance data from a 16-node execution of AMG2006 on vesta.
The data collected isn't the problem. I was able to analyze the performance data on gpu.cs

Reproducer: (binary, struct file, submission script for hpcprof-mpi, measurements database)
https://rice.box.com/s/1o18z7su1rfahrpbuc189x1u1anus49s

Failure symptom:

```
Core was generated by `/home/johnmc/atpesc18/hpctoolkit/INSTALL-vesta-g/bin/hpcprof-mpi'.
Program terminated with signal 11, Segmentation fault.

#0  _int_free (av=0x1e16d48, p=0x1dc6ca4e50, have_lock=Unhandled dwarf expression opcode 0xf3
) at malloc.c:3882
#1  0x00000000017b1698 in operator delete (ptr=<value optimized out>)
    at /bgsys/drivers/V1R2M4/ppc64/toolchain-4.7.2/gnu/gcc-4.7.2/libstdc++-v3/libsupc++/del_op.cc:48
#2  0x000000000181c960 in deallocate (this=<value optimized out>, __a=<value optimized out>)
    at /bgsys/drivers/V1R2M4/ppc64/toolchain-4.7.2/gnu/build-powerpc64-bgq-linux/gcc-4.7.2-build/powerpc64-bgq-linux/libstdc++-v3/include/ext/new_allocator.h:100
#3  std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_M_destroy (this=<value optimized out>, __a=<value optimized out>)
    at /bgsys/drivers/V1R2M4/ppc64/toolchain-4.7.2/gnu/build-powerpc64-bgq-linux/gcc-4.7.2-build/powerpc64-bgq-linux/libstdc++-v3/include/bits/basic_string.tcc:451
#4  0x00000000017f0120 in _M_dispose (this=0x1fbfff9d08, __in_chrg=<value optimized out>, __vtt_parm=<value optimized out>)
    at /bgsys/drivers/V1R2M4/ppc64/toolchain-4.7.2/gnu/build-powerpc64-bgq-linux/gcc-4.7.2-build/powerpc64-bgq-linux/libstdc++-v3/include/bits/basic_string.h:246
#5  ~basic_string (this=0x1fbfff9d08, __in_chrg=<value optimized out>, __vtt_parm=<value optimized out>)
    at /bgsys/drivers/V1R2M4/ppc64/toolchain-4.7.2/gnu/build-powerpc64-bgq-linux/gcc-4.7.2-build/powerpc64-bgq-linux/libstdc++-v3/include/bits/basic_string.h:536
#6  ~basic_stringbuf (this=0x1fbfff9d08, __in_chrg=<value optimized out>, __vtt_parm=<value optimized out>)
    at /bgsys/drivers/V1R2M4/ppc64/toolchain-4.7.2/gnu/build-powerpc64-bgq-linux/gcc-4.7.2-build/powerpc64-bgq-linux/libstdc++-v3/include/sstream:60
#7  std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream (this=0x1fbfff9d08, 
    __in_chrg=<value optimized out>, __vtt_parm=<value optimized out>)
    at /bgsys/drivers/V1R2M4/ppc64/toolchain-4.7.2/gnu/build-powerpc64-bgq-linux/gcc-4.7.2-build/powerpc64-bgq-linux/libstdc++-v3/include/sstream:439
#8  0x00000000010b7410 in Prof::CallPath::Profile::fmt_epoch_fread (prof=@0x1fbfff9f48, infs=0x1dc6ca3fc0, rFlags=9, hdr=..., ctxtStr=..., 
    filename=0x0, outfs=0x0) at ../../../../src/lib/prof/CallPath-Profile.cpp:1345
#9  0x00000000010b4bcc in Prof::CallPath::Profile::fmt_fread (prof=@0x1fbfffa1d8, infs=0x1dc6ca3fc0, rFlags=1, ctxtStr=..., filename=0x0, outfs=0x0)
    at ../../../../src/lib/prof/CallPath-Profile.cpp:970
#10 0x000000000100ebf4 in ._ZN16ParallelAnalysis13unpackProfileEPhm () at ../../../../src/tool/hpcprof-mpi/ParallelAnalysis.cpp:348
#11 0x000000000100e9c0 in ._ZN16ParallelAnalysis13mergeNonLocalEPN4Prof8CallPath7ProfileEiiii ()
    at ../../../../src/tool/hpcprof-mpi/ParallelAnalysis.cpp:175
#12 0x00000000010085f8 in ._ZN16ParallelAnalysis6reduceIPN4Prof8CallPath7ProfileEEEvT_iii ()
    at ../../../../src/tool/hpcprof-mpi/ParallelAnalysis.hpp:354
#13 0x000000000100543c in ._ZL8realmainiPKPc () at ../../../../src/tool/hpcprof-mpi/main.cpp:290
#14 0x0000000001004950 in .main () at ../../../../src/tool/hpcprof-mpi/main.cpp:180

```

HPCToolkit details:

- ompt-tr4 branch, commit f6cdb03b6f1506fbfa86b3420008d82a91d18440

- ../configure --prefix=/home/johnmc/atpesc18/hpctoolkit/BUILD-vesta-g/../INSTALL-vesta-g --with-externals=/home/johnmc/atpesc18/hpctoolkit/BUILD-vesta/../../hpctoolkit-externals/INSTALL-vesta HPCPROFMPI_LT_LDFLAGS=-all-static --enable-develop --no-create --no-recursion

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/93)
